#!/usr/bin/env python3
"""
Local DB Table Lister - Lists all tables and their content from app.db using MCP server.
Version: 0.1
Generated by MCP Server Creator on 2025-09-17 23:11:23
"""

from fastmcp import FastMCP, Context

# Initialize the MCP server
mcp = FastMCP(
    "Local DB Table Lister",
    instructions="""Lists all tables and their content from app.db using MCP server."""
)

# Tools

@mcp.tool()
def list_tables() -> list:
    """Lists all tables in the SQLite database app.db."""
    import sqlite3
    conn = sqlite3.connect('app.db')
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = [row[0] for row in cursor.fetchall()]
    conn.close()
    return tables

@mcp.tool()
def get_table_content(table_name: str) -> dict:
    """Returns all content from a specified table in app.db."""
    import sqlite3
    conn = sqlite3.connect('app.db')
    cursor = conn.cursor()
    cursor.execute(f"SELECT * FROM \"{table_name}\"")
    rows = cursor.fetchall()
    columns = [description[0] for description in cursor.description]
    conn.close()
    return {'columns': columns, 'rows': rows}

if __name__ == "__main__":
    mcp.run()
